// <auto-generated />
using Ilusalong.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ilusalong.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240510144203_updateAddedProtseduurid")]
    partial class updateAddedProtseduurid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ilusalong.Models.Kasutajad", b =>
                {
                    b.Property<int>("KasutajadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KasutajadID"));

                    b.Property<string>("kas_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kas_nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kas_parool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kas_pernimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kas_telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roll")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KasutajadID");

                    b.ToTable("Kasutajad");
                });

            modelBuilder.Entity("Ilusalong.Models.Kategooriad", b =>
                {
                    b.Property<int>("KategooriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategooriaID"));

                    b.Property<string>("kat_nimetus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategooriaID");

                    b.ToTable("Kategooria");
                });

            modelBuilder.Entity("Ilusalong.Models.Meistrid", b =>
                {
                    b.Property<int>("MeistridID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeistridID"));

                    b.Property<string>("master_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("master_eriala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("master_nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("master_pernimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("master_telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeistridID");

                    b.ToTable("Meistrid");
                });

            modelBuilder.Entity("Ilusalong.Models.Protseduurid", b =>
                {
                    b.Property<int>("ProtseduurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProtseduurID"));

                    b.Property<string>("Aeg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kas_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kas_nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kas_telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("master_nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("master_pernimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nimetus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProtseduurID");

                    b.ToTable("Protseduurid");
                });

            modelBuilder.Entity("Ilusalong.Models.Tooted", b =>
                {
                    b.Property<int>("ToodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToodeID"));

                    b.Property<float>("Hind")
                        .HasColumnType("real");

                    b.Property<int>("KategooriaId")
                        .HasColumnType("int");

                    b.Property<string>("Kirjeldus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nimetus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToodeID");

                    b.ToTable("Toode");
                });
#pragma warning restore 612, 618
        }
    }
}
